# Generated by Django 3.0.2 on 2020-01-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('language', models.CharField(max_length=50, verbose_name='Course language')),
                ('price', models.CharField(max_length=10, verbose_name='Course price')),
            ],
        ),
    ]
